services:
  api-gateway:
    image: jefferson661/gateway-app
    container_name: api-gateway
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    depends_on:
      - eureka-server
      - newsletter-api
      - empresa-api
  eureka-server:
    image: jefferson661/eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  postgres:
    image: postgres
    container_name: postgressql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  empresa-api:
    image: jefferson661/empresa-api
    container_name: empresa-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server

  servico-api:
    image: jefferson661/servico-app
    container_name: servico-api
    networks:
      - mynetwork
    ports:
      - "8089:8089"
    depends_on:
      - postgres
      - eureka-server

  prestadora-api:
    image: jefferson661/prestadora-app
    container_name: prestadora-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server

  newsletter-api:
    image: jefferson661/newsletter-app
    container_name: newsletter-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server
      - empresa-api

  meta-api:
    image: jefferson661/meta-api
    container_name: meta-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server

  interacao-api:
    image: jefferson661/interacao-app
    container_name: interacao-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server

  questionario-api:
    image: jefferson661/questionario-api
    container_name: questionario-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server

  portfolio-api:
    image: vitorxp/portfolio-app
    container_name: portfolio-api
    networks:
      - mynetwork
    depends_on:
      - postgres
      - eureka-server
    ports:
      - "8088:8088"

networks:
  mynetwork:
    external: true
volumes:
  postgres-data: