services:
  api-gateway:
    image: jefferson661/gateway-app
    container_name: api-gateway
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - eureka-server
  eureka-server:
    image: jefferson661/eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynetwork
networks:
  mynetwork:
    external: false