services:
  api-gateway:
    image: jefferson661/gateway-app
    container_name: api-gateway
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    depends_on:
      - eureka-server
      - newsletter-api
      - empresa-api
  eureka-server:
    image: jefferson661/eureka-server
    ports:
      - "8761:8761"
    networks:
      - mynetwork
  postgres:
    image: postgres
    container_name: postgressql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    networks:
      - mynetwork
  postgres-empresa:
    image: postgres
    container_name: postgres-empresa
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5435:5432"
    networks:
      - mynetwork
  empresa-api:
    image: jefferson661/empresa-api
    container_name: empresa-api
    networks:
      - mynetwork
    depends_on:
      - postgres-empresa
      - eureka-server
  newsletter-api:
    image: jefferson661/newsletter-app
    container_name: newsletter-api
    networks:
      - mynetwork
    depends_on:
      - postgres-newsletter
      - eureka-server
      - empresa-api
  postgres-newsletter:
    image: postgres
    container_name: postgres-newsletter
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5434:5432"
    networks:
      - mynetwork
  servico-api:
    image: jefferson661/servico-app
    container_name: servico-api
    networks:
      - mynetwork
    depends_on:
      - postgres-servico
      - eureka-server
  postgres-servico:
    image: postgres
    container_name: postgres-servico
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5436:8089"
    networks:
      - mynetwork
  postgres-prestadora:
    image: postgres
    container_name: postgres-prestadora
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5437:5432"
    networks:
      - mynetwork
  postgres-avaliacao:
    image: postgres
    container_name: postgres-avaliacao
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5438:5432"
    networks:
      - mynetwork
  postgres-portfolio:
    image: postgres
    container_name: postgres-portfolio
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5439:5432"
    networks:
      - mynetwork
  postgres-pergunta:
    image: postgres
    container_name: postgres-pergunta
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5440:5432"
    networks:
      - mynetwork
  postgres-meta:
    image: postgres
    container_name: postgres-meta
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5441:5432"
    networks:
      - mynetwork
  meta-api:
    image: jefferson661/meta-api
    container_name: meta-api
    networks:
      - mynetwork
    depends_on:
      - postgres-meta
      - eureka-server
  interacao-api:
    image: jefferson661/interacao-app
    container_name: interacao-api
    networks:
      - mynetwork
    depends_on:
      - postgres-interacao
      - eureka-server
  postgres-interacao:
    image: postgres
    container_name: postgres-interacao
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5442:5432"
    networks:
      - mynetwork
  questionario-api:
    image: jefferson661/questionario-api
    container_name: questionario-api
    networks:
      - mynetwork
    depends_on:
      - postgres-pergunta
      - eureka-server


networks:
  mynetwork:
    external: true
volumes:
  postgres-data: