name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create network
        run: docker network create -d bridge --subnet=172.23.0.1/16 --gateway=172.23.0.1 mynetwork

      - name: Set up Docker Compose
        run: docker-compose -f stack.yaml up -d

      - name: Connect to PostgreSQL
        run: docker exec postgressql psql -h localhost -U admin -d postgres

      - name: Run Makefile
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: make local-env-create


      - name: Clean up
        run: make local-env-destroy
